version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongoDB
    ports:
      - 27017:27017 # default port for mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db_data/:/data/db/


# connection string for mongoDB: mongodb://<username>:<password>@localhost:27017