version: "3"
services:
  db:
    image: postgres:14.1 # using this version of postgres for postgis
    restart: always # restart if container fails
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432 # default postgres port

    environment:
      - POSTGRES_DB=theekke
      - POSTGRES_USER=sunny # change this to your username
      - POSTGRES_PASSWORD=root # change this to your password

    command: >
      bash -c "apt-get update && apt-get install -y postgresql-14-postgis-3 && /usr/local/bin/docker-entrypoint.sh postgres"

  adminer: # use latest official adminer version
    image: adminer
    restart: always # restart if container fails
    ports:
      - 8080:8080
